[pytest]
markers =
    test_metadata: Custom marker for test metadata.
    e2e: Marker for end-to-end tests.
    ui: Marker for UI tests.
    api: Marker for API tests.
    unit: Marker for unit tests.
    integration: Marker for integration tests.